# coding:utf8
__author__ = 'Marcelo Ferreira da Costa Gomes'
import pandas as pd

dict_dtypes = {
    'NU_NOTIFIC': 'str',
    'DT_NOTIFIC': 'str',
    'SEM_NOT': 'float64',
    'DT_SIN_PRI': 'str',
    'SEM_PRI': 'float64',
    'SG_UF_NOT': 'str',
    'ID_REGIONA': 'str',
    'CO_REGIONA': 'float64',
    'ID_MUNICIP': 'str',
    'CO_MUN_NOT': 'float64',
    'ID_UNIDADE': 'str',
    'CO_UNI_NOT': 'float64',
    'NM_UN_INTE': 'str',
    'CO_UN_INTE': 'float64',
    'LAB_AN': 'str',
    'CO_LAB_AN': 'float64',
    'RES_CAPITAL': 'str',
    'NOT_CAPITAL': 'str',
    'NU_CPF': 'str',
    'NM_PACIENT': 'str',
    'CS_SEXO': 'str',
    'DT_NASC': 'str',
    'NU_IDADE_N': 'str',
    'TP_IDADE': 'float64',
    'COD_IDADE': 'str',
    'CS_GESTANT': 'float64',
    'CS_RACA': 'float64',
    'CS_ETINIA': 'str',
    'CS_ESCOL_N': 'float64',
    'NM_MAE_PAC': 'str',
    'NU_CEP': 'str',
    'ID_PAIS': 'str',
    'CO_PAIS': 'float64',
    'SG_UF': 'str',
    'ID_RG_RESI': 'str',
    'CO_RG_RESI': 'float64',
    'ID_MN_RESI': 'str',
    'CO_MUN_RES': 'float64',
    'NM_BAIRRO': 'str',
    'NM_LOGRADO': 'str',
    'NU_NUMERO': 'str',
    'NM_COMPLEM': 'str',
    'NU_DDD_TEL': 'float64',
    'NU_TELEFON': 'str',
    'CS_ZONA': 'float64',
    'SURTO_SG': 'float64',
    'NOSOCOMIAL': 'float64',
    'AVE_SUINO': 'float64',
    'FEBRE': 'float64',
    'TOSSE': 'float64',
    'GARGANTA': 'float64',
    'DISPNEIA': 'float64',
    'DESC_RESP': 'float64',
    'SATURACAO': 'float64',
    'DIARREIA': 'float64',
    'VOMITO': 'float64',
    'OUTRO_SIN': 'float64',
    'OUTRO_DES': 'str',
    'PUERPERA': 'float64',
    'FATOR_RISC': 'str',
    'CARDIOPATI': 'float64',
    'HEMATOLOGI': 'float64',
    'SIND_DOWN': 'float64',
    'HEPATICA': 'float64',
    'ASMA': 'float64',
    'DIABETES': 'float64',
    'NEUROLOGIC': 'float64',
    'PNEUMOPATI': 'float64',
    'IMUNODEPRE': 'float64',
    'RENAL': 'float64',
    'OBESIDADE': 'float64',
    'OBES_IMC': 'str',
    'OUT_MORBI': 'float64',
    'MORB_DESC': 'str',
    'VACINA': 'float64',
    'DT_UT_DOSE': 'str',
    'MAE_VAC': 'float64',
    'DT_VAC_MAE': 'str',
    'M_AMAMENTA': 'float64',
    'DT_DOSEUNI': 'str',
    'DT_1_DOSE': 'str',
    'DT_2_DOSE': 'str',
    'ANTIVIRAL': 'float64',
    'TP_ANTIVIR': 'float64',
    'OUT_ANTIV': 'str',
    'DT_ANTIVIR': 'str',
    'HOSPITAL': 'float64',
    'DT_INTERNA': 'str',
    'SG_UF_INTE': 'str',
    'ID_RG_INTE': 'str',
    'CO_RG_INTE': 'float64',
    'ID_MN_INTE': 'str',
    'CO_MU_INTE': 'float64',
    'UTI': 'float64',
    'DT_ENTUTI': 'str',
    'DT_SAIDUTI': 'str',
    'SUPORT_VEN': 'float64',
    'RAIOX_RES': 'float64',
    'RAIOX_OUT': 'str',
    'DT_RAIOX': 'str',
    'AMOSTRA': 'float64',
    'DT_COLETA': 'str',
    'TP_AMOSTRA': 'float64',
    'OUT_AMOST': 'str',
    'REQUI_GAL': 'float64',
    'IF_RESUL': 'float64',
    'DT_IF': 'str',
    'POS_IF_FLU': 'float64',
    'TP_FLU_IF': 'float64',
    'POS_IF_OUT': 'float64',
    'IF_VSR': 'float64',
    'IF_PARA1': 'float64',
    'IF_PARA2': 'float64',
    'IF_PARA3': 'float64',
    'IF_ADENO': 'float64',
    'IF_OUTRO': 'float64',
    'DS_IF_OUT': 'object',
    'LAB_IF': 'str',
    'CO_LAB_IF': 'float64',
    'PCR_RESUL': 'float64',
    'DT_PCR': 'str',
    'POS_PCRFLU': 'float64',
    'TP_FLU_PCR': 'float64',
    'PCR_FLUASU': 'float64',
    'FLUASU_OUT': 'str',
    'PCR_FLUBLI': 'float64',
    'FLUBLI_OUT': 'str',
    'POS_PCROUT': 'float64',
    'PCR_VSR': 'float64',
    'PCR_PARA1': 'float64',
    'PCR_PARA2': 'float64',
    'PCR_PARA3': 'float64',
    'PCR_PARA4': 'float64',
    'PCR_ADENO': 'float64',
    'PCR_METAP': 'float64',
    'PCR_BOCA': 'float64',
    'PCR_RINO': 'float64',
    'PCR_OUTRO': 'float64',
    'DS_PCR_OUT': 'str',
    'LAB_PCR': 'str',
    'CO_LAB_PCR': 'float64',
    'CLASSI_FIN': 'float64',
    'CLASSI_OUT': 'str',
    'CRITERIO': 'float64',
    'EVOLUCAO': 'float64',
    'DT_EVOLUCA': 'str',
    'NU_DO': 'float64',
    'DT_ENCERRA': 'str',
    'OBSERVA': 'str',
    'NOME_PROF': 'str',
    'REG_PROF': 'str',
    'DT_DIGITA': 'str',
    'HISTO_VGM': 'float64',
    'PAIS_VGM': 'str',
    'CO_PS_VGM': 'float64',
    'LO_PS_VGM': 'str',
    'DT_VGM': 'str',
    'DT_RT_VGM': 'str',
    'PCR_SARS2': 'float64',
    'PAC_COCBO': 'str',
    'PAC_DSCBO': 'str',
    'OUT_ANIM': 'str',
    'DOR_ABD': 'float64',
    'FADIGA': 'float64',
    'PERD_OLFT': 'float64',
    'PERD_PALA': 'float64',
    'TOMO_RES': 'float64',
    'TOMO_OUT': 'str',
    'DT_TOMO': 'str',
    'TP_TES_AN': 'float64',
    'DT_RES_AN': 'str',
    'RES_AN': 'float64',
    'POS_AN_FLU': 'float64',
    'TP_FLU_AN': 'float64',
    'POS_AN_OUT': 'float64',
    'AN_SARS2': 'float64',
    'AN_VSR': 'float64',
    'AN_PARA1': 'float64',
    'AN_PARA2': 'float64',
    'AN_PARA3': 'float64',
    'AN_ADENO': 'float64',
    'AN_OUTRO': 'float64',
    'DS_AN_OUT': 'str',
    'TP_AM_SOR': 'float64',
    'SOR_OUT': 'str',
    'DT_CO_SOR': 'str',
    'TP_SOR': 'float64',
    'OUT_SOR': 'str',
    'DT_RES': 'str',
    'RES_IGG': 'float64',
    'RES_IGM': 'float64',
    'RES_IGA': 'float64',
    'DT_ATUALIZACAO': 'str',
    '@VERSION': 'int64',
    '@TIMESTAMP': 'str'
}
df = (pd.concat([pd.read_csv('../data/INFLUD2020.csv',
                             dtype=dict_dtypes, low_memory=False),
                 pd.read_csv('../data/INFLUD2021.csv',
                             dtype=dict_dtypes, low_memory=False)],
                ignore_index=True, sort=False)
      )[['NU_NOTIFIC',
         'DT_NOTIFIC',
         'DT_SIN_PRI',
         'DT_INTERNA',
         'DT_DIGITA',
         'DT_EVOLUCA',
         'SG_UF',
         'SG_UF_NOT',
         'CO_MUN_NOT',
         'CO_MUN_RES',
         'NU_CPF',
         'NM_PACIENT',
         'CS_SEXO',
         'DT_NASC',
         'NM_MAE_PAC',
         'CLASSI_FIN',
         'CRITERIO'
         ]]
df.to_csv('../clean_data/srag_2020_2021_reinfecslice.csv.gz',
          index=False,
          compression='gzip')
