#' Calculates RR and SR for sragcovid and obitocovid with respect to vacination status
#' by age bracket and month os symptoms onset.
#' 
#' Expects df with same structure as the final dadosBR.vac.hosp.2
#' generated by vac.hosp.R

sr.rr.vac <- function(df){
  if (is.null(df)){
    warning('Empty data')
    return(NULL)
  }
  rr <- df %>%
    select(-eventos, -pop) %>%
    pivot_wider(names_from=dado,
                values_from = frac) %>%
    mutate(sr.hosp = sragcovid/pop,
           sr.obitocovid = obitocovid/pop)
  rr <- rr %>%
    filter(!(ano==2022 & mes > 1),
           !is.na(fx_etaria)) %>%
    pivot_longer(cols=c(pop, sragcovid, obitocovid), names_to = 'dado',
                 values_to = 'frac') %>%
    mutate(sr = case_when(
      dado == 'sragcovid' ~ as.numeric(sr.hosp),
      dado == 'obitocovid' ~ as.numeric(sr.obitocovid),
      TRUE ~ NA_real_
    )) %>%
    select(-sr.hosp, -sr.obitocovid) %>%
    pivot_wider(names_from=vac_completa, values_from=c(frac, sr)) %>%
    mutate(rr = sr_não / sr_sim)
  
  return(rr)  
}

plot.rr.vac <- function(rr,
                        scale='free_y',
                        base_size=14,
                        base_family='Roboto',
                        sigla='BR',
                        title=paste0(sigla, ': ', 'Risco relativo de SRAG e óbito por COVID-19'),
                        subtitle=paste0('Razão de incidências entre pop. sem e com duas doses ou dose única por faixa etária e mês de início de sintomas.\n',
                                        'Dados do SIVEP-Gripe digitados até a semana ', epiweek, ' de ', lyear, '.')){
  rr %>%
    mutate(dt_sinpri = ym(paste0(ano, mes))) %>%
    filter(DS_UF_SIGLA == sigla,
           !fx_etaria %in% c('0-4', '5-11', 'Total', 'Total(10+)', NA),
           dado != 'pop',
           dt_sinpri < '2022-02-01') %>%
    ggplot(aes(x=dt_sinpri, y=rr, color=dado)) +
    geom_hline(yintercept = 1, color='gray', linetype=2, size=1.5) +
    geom_line() +
    scale_color_colorblind(labels=c('Óbitos', 'Internações'), name='') +
    scale_x_date(date_labels = "%b",date_breaks = "1 month") +
    labs(x='Mês de início de sintomas',
         y='Risco relativo') +
    facet_wrap(~fx_etaria, scale=scale) +
    theme_Publication(base_family=base_family, base_size=base_size)+
    ggtitle(title,
            subtitle=subtitle) +
    theme(legend.position = 'bottom',
          legend.direction = 'horizontal') %>%
    return()
}

plot.sr.vac <- function(rr,
                        scale='free_y',
                        base_size=14,
                        base_family='Roboto',
                        sigla='BR',
                        title=paste0(sigla, ': ', 'Sobrerrisco de SRAG e óbito por COVID-19'),
                        subtitle=paste0('Comparação entre pop. sem duas doses ou dose única e pop. geral por faixa etária e mês de início de sintomas.\n',
                                        'Dados do SIVEP-Gripe digitados até a semana 4 de 2022.')){
  rr %>%
    mutate(dt_sinpri = ym(paste0(ano, mes))) %>%
    filter(DS_UF_SIGLA == sigla,
           !fx_etaria %in% c('0-4', '5-11', 'Total', 'Total(10+)', NA),
           dado != 'pop',
           dt_sinpri < '2022-02-01') %>%
    ggplot(aes(x=dt_sinpri, y=sr_não, color=dado)) +
    geom_hline(yintercept = 1, color='gray', linetype=2, size=1.5) +
    geom_line() +
    scale_color_colorblind(labels=c('Óbitos', 'Internações'), name='') +
    scale_x_date(date_labels = "%b",date_breaks = "1 month") +
    labs(x='Mês de início de sintomas',
         y='Sobrerrisco\npara indivíduos sem D2 ou DU') +
    facet_wrap(~fx_etaria, scale=scale) +
    theme_Publication(base_family=base_family, base_size=base_size)+
    ggtitle(title,
            subtitle=subtitle) +
    theme(legend.position = 'bottom',
          legend.direction = 'horizontal') %>%
    return()
}